// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd-5KMQP0iLeQ6BtfQYExwz5JZKCd2Kyk',
    appId: '1:765003588447:web:7fab6c4b81059839d0ccea',
    messagingSenderId: '765003588447',
    projectId: 'campus-93a4c',
    authDomain: 'campus-93a4c.firebaseapp.com',
    storageBucket: 'campus-93a4c.firebasestorage.app',
    measurementId: 'G-NFND8Q5JS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzAklvR-EOm7YBZt8M827dpn6sFRkhKxw',
    appId: '1:765003588447:android:960953a39cf6ee34d0ccea',
    messagingSenderId: '765003588447',
    projectId: 'campus-93a4c',
    storageBucket: 'campus-93a4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFowYIHrH3VTb2TUb8KRE9zhLORSecKfY',
    appId: '1:765003588447:ios:4f7995440b0a2fb7d0ccea',
    messagingSenderId: '765003588447',
    projectId: 'campus-93a4c',
    storageBucket: 'campus-93a4c.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFowYIHrH3VTb2TUb8KRE9zhLORSecKfY',
    appId: '1:765003588447:ios:4f7995440b0a2fb7d0ccea',
    messagingSenderId: '765003588447',
    projectId: 'campus-93a4c',
    storageBucket: 'campus-93a4c.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd-5KMQP0iLeQ6BtfQYExwz5JZKCd2Kyk',
    appId: '1:765003588447:web:bb6eae4772cf4a78d0ccea',
    messagingSenderId: '765003588447',
    projectId: 'campus-93a4c',
    authDomain: 'campus-93a4c.firebaseapp.com',
    storageBucket: 'campus-93a4c.firebasestorage.app',
    measurementId: 'G-2HSMW1SNQ4',
  );
}
