// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTbeKaG4pLh7YWwUSNUC_6_IQHa0vLs7Y',
    appId: '1:816678543056:web:dc09fbd8f87213a904c8d5',
    messagingSenderId: '816678543056',
    projectId: 'week5-project-b4f65',
    authDomain: 'week5-project-b4f65.firebaseapp.com',
    storageBucket: 'week5-project-b4f65.firebasestorage.app',
    measurementId: 'G-Y02J57F40D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWMBGRTnuO5YOUUMlkL5ss2sQFpa9qrIE',
    appId: '1:816678543056:android:00d790d4da23282e04c8d5',
    messagingSenderId: '816678543056',
    projectId: 'week5-project-b4f65',
    storageBucket: 'week5-project-b4f65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBboPnsrJr83jTCNAXr7aV08kyxnqrmEwg',
    appId: '1:816678543056:ios:ca350586a808e45e04c8d5',
    messagingSenderId: '816678543056',
    projectId: 'week5-project-b4f65',
    storageBucket: 'week5-project-b4f65.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBboPnsrJr83jTCNAXr7aV08kyxnqrmEwg',
    appId: '1:816678543056:ios:ca350586a808e45e04c8d5',
    messagingSenderId: '816678543056',
    projectId: 'week5-project-b4f65',
    storageBucket: 'week5-project-b4f65.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTbeKaG4pLh7YWwUSNUC_6_IQHa0vLs7Y',
    appId: '1:816678543056:web:97583a7d48ea8dba04c8d5',
    messagingSenderId: '816678543056',
    projectId: 'week5-project-b4f65',
    authDomain: 'week5-project-b4f65.firebaseapp.com',
    storageBucket: 'week5-project-b4f65.firebasestorage.app',
    measurementId: 'G-MC6LP3EHNE',
  );
}
